apiVersion: 1
datasources:
  - name: Prometheus
    uid: blocky-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
  - name: BlockyLogs
    uid: blocky-mysql
    type: mysql
    access: proxy
    url: 127.0.0.1:3307
    user: blocky
    database: blocky
    editable: false
    jsonData:
      database: blocky
      timezone: '+00:00'
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 300
    secureJsonData:
      password: $BLOCKY_DB_PASSWORD
